// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attendance struct {
	ID         pgtype.UUID
	StudentID  pgtype.UUID
	ScheduleID pgtype.UUID
	Here       bool
	Counter    int32
}

type Homework struct {
	ID        pgtype.UUID
	TeacherID pgtype.UUID
	LessonID  pgtype.UUID
	ClassID   pgtype.UUID
	Title     string
	Content   pgtype.Text
	DueDate   pgtype.Timestamp
}

type Lesson struct {
	ID         pgtype.UUID
	LessonName string
}

type Schedule struct {
	ID        pgtype.UUID
	Date      pgtype.Date
	Time      pgtype.Time
	TeacherID pgtype.UUID
	LessonID  pgtype.UUID
	ClassID   pgtype.UUID
}
